### PR TITLE
Remove MITIE; Add it as a submodule instead.

### PR DESCRIPTION
**Pull request by andylolz**
Hi @wrrrrn – if you get a chance, could you have a go at this? It probably involves installing from scratch… I’ve added some [installation instructions to the README](https://github.com/spudmind/spud/blob/d22915bb/README.md#installation).

### CODE REVIEW

**Comment by andylolz** [comment]
@wrrrrn if you get a chance, can you look at this? I’m switching branches constantly.d

**Comment by wrrrrn** [comment]
Have you tried the pre-compiled version yet?

**Comment by andylolz** [comment]
Yep. Doesn’t work. Unless I am doing something wrong. I am unzipping the contents of the [zip downloaded here](https://github.com/mit-nlp/MITIE#precompiled-python-27-binaries) into utils/mitie.

If that’s wrong, can you update README with installation instructions.

**Comment by wrrrrn** [comment]
Ah ok. going to double check the pre-compiled download now and confirm its the same. If so, I'll install from scratch

**Pull request merged**
